# @package _global_
# problem args

problem: "cvrp"
graph_size: 100
coords_dist: "gm_unif_mixed"
weights_dist: "random_k_variant"
out_name: ${problem}_${graph_size}_${coords_dist}
data_file_path:
checkpoint_load_path: models/DACT/DACT/pretrained/cvrp100-epoch-198.pt
heatmap_load_path: models/DPDP/DPDP/results/${problem}/${problem}_${coords_dist}100_val_seed4321/heatmaps/heatmaps_${problem}_${coords_dist}100.pkl
normalize_data: False


# RP Env cfg
env_kwargs:
  generator_args:
    coords_sampling_dist: ${coords_dist}
    weights_sampling_dist: ${weights_dist}
    mu_sampling_dist: "normal"
    mu_sampling_params: [ 0, 1 ]
    sigma_sampling_dist: "uniform"
    sigma_sampling_params: [ 0.05, 0.1 ]
    n_components: [ 1, 10 ]
    uniform_fraction: [ 0.5, 9 ]
  sampling_args:
    sample_size: 64
    graph_size: ${graph_size}
    k: 32
    cap: 50
    n_depots: 1 #number of depots (default = 1)