# @package _global_
# problem args

problem: "cvrp"
graph_size: 50
coords_dist: 'uniform'
out_name: ${problem}_${graph_size}_${coords_dist}
data_file_path: data/test_data/${problem}/${coords_dist}/${problem}${graph_size}/val_seed123_size512.pt
normalize_data: False
checkpoint_load_path: models/DPDP/DPDP/logs/${problem}_${coords_dist}100/best_val_loss_checkpoint.tar
heatmap_load_path: models/DPDP/DPDP/results/${problem}/${problem}_${coords_dist}100_val_seed4321/heatmaps/heatmaps_${problem}_${coords_dist}100.pkl


# RP Env cfg
env_kwargs:
  generator_args:
    coords_sampling_dist: ${coords_dist}
    weights_sampling_dist: random_int # sampling integers from 1-10
    normalize_demands: False  # if None or False - demands will remain un-normalized (not between 0-1)
    single_large_instance: data/train_data/${problem}_10000/${coords_dist}/single_large_instance.pt
  sampling_args:
    sample_size: 1024
    graph_size: ${graph_size}
    subsample: False
    k: 16
    cap: 50