# @package _global_
# problem args

problem: "tsp"
graph_size: 100
coords_dist: "uniform_fu"
out_name: ${problem}_${graph_size}_${coords_dist}
data_file_path: data/test_data/tsp/uniform/fu/tsp${graph_size}_fu.pt
normalize_data: True
checkpoint_load_path: models/AM/AM/pretrained/${problem}_100/uniform/epoch-99.pt
trained_model_args_path: models/AM/AM/pretrained/${problem}_100/uniform/args.json

# RP Env cfg
env_kwargs:
  generator_args:
    coords_sampling_dist: uniform
    single_large_instance: # data/train_data/${problem}/${coords_dist}/single_large_instance.pt
  sampling_args:
    sample_size: 128
    graph_size: ${graph_size}
    subsample: False
