# @package _global_
# problem args

problem: "cvrp"
graph_size: 100
coords_dist: 'rotation'
weights_dist: 'random_int'  # sampling integers from 1-10
out_name: ${problem}_${graph_size}_${coords_dist}_sub
data_file_path: data/test_data/${problem}/sub_${coords_dist}/${problem}${graph_size}/val_seed5588_size128.pt

normalize_data: True
checkpoint_load_path: models/POMO/POMO/cvrp/POMO/result/saved_CVRP100_model/rotation_sub/cvrp100/checkpoint-8100.pt

# RP Env cfg
env_kwargs:
  generator_args:
    coords_sampling_dist: ${coords_dist}
    weights_sampling_dist: ${weights_dist}
    normalize_demands: True  # if None or False - demands will remain un-normalized (not between 0-1)
    single_large_instance: # data/train_data/${problem}_10000/${coords_dist}_rndint/single_large_instance.pt
    # following parameter defines the anchor at which the uniform coordinates are mutated aka rotated
    pm: 0.4
  sampling_args:
    sample_size: 128 # 1024
    graph_size: ${graph_size}
    subsample: True
    k: 16 # 25-30 for 200
    cap: 50  # 70 for 200
    max_cap_factor: # factor of additional capacity w.r.t. a norm capacity of 1.0 per vehicle
    n_depots: 1 #number of depots (default = 1)

# Model Env cfg
env_cfg:
  problem_size: ${graph_size}
  pomo_size: ${tester_cfg.pomo_size}
  generator_args:
    coords_dist: ${coords_dist}
    graph_size: ${graph_size}