# @package _global_
# problem args

problem: "tsp"
graph_size: 100
coords_dist: 'rotation'
out_name: ${problem}_${graph_size}_${coords_dist}
data_file_path: data/test_data/tsp/rotation/tsp100/val_seed4321_size128.pt

normalize_data: True
checkpoint_load_path: models/POMO/POMO/tsp/POMO/result/rotation/saved_tsp100_model/checkpoint-8100.pt

# models/POMO/POMO/cvrp/POMO/result/saved_CVRP100_model/uniform_sub/checkpoint-100.pt
# models/POMO/POMO/${problem}/POMO/result/saved_CVRP100_model/${coords_dist}/checkpoint-30500.pt
# models/POMO/POMO/cvrp/POMO/result/saved_CVRP100_model/uniform_sub/checkpoint-100.pt

# RP Env cfg
env_kwargs:
  generator_args:
    coords_sampling_dist: ${coords_dist}
    single_large_instance: # data/train_data/${problem}_10000/${coords_dist}/single_large_instance.pt
    pm: 0.6
    angle_range: [1.2, 1.9] # --> uniform(1.2, 1.3*pi) - default for problem size 200 is unif(0, 2*pi)
  sampling_args:
    sample_size: 128
    graph_size: ${graph_size}
    subsample: False
    n_depots: 1 #number of depots (default = 1)


# Model Env cfg
env_cfg:
  problem_size: ${graph_size}
  pomo_size: ${tester_cfg.pomo_size}
  generator_args:
    coords_dist: ${coords_dist}
    graph_size: ${graph_size}