# @package _global_
# problem args

problem: "cvrp"
graph_size: 100
coords_dist: "gm"
weights_dist: "gamma"
out_name: ${problem}_${graph_size}_${coords_dist}
data_file_path: data/test_data/${problem}/${coords_dist}_${weights_dist}/${problem}${graph_size}/val_seed1234_size128.pkl
# checkpoint in model cfg yaml
normalize_data: False
k_sparse: 20

# RP Env cfg
env_kwargs:
  generator_args:
    coords_sampling_dist: ${coords_dist}
    weights_sampling_dist: ${weights_dist}
    normalize_demands: False  # if None or False - demands will remain un-normalized (not between 0-1)
    single_large_instance: # data/train_data/${problem}_10000/${coords_dist}/single_large_instance.pt
    mu_sampling_dist: "normal"
    mu_sampling_params: [ 0, 1 ]
    sigma_sampling_dist: "uniform"
    sigma_sampling_params: [ 0.05, 0.1 ]
    n_components: [ 1, 10 ]
    uniform_fraction: [ 0.5, 9 ]
  sampling_args:
    sample_size: 64
    graph_size: ${graph_size}
    subsample: False
    k: 32
    cap: 50
    n_depots: 1 #number of depots (default = 1)
    max_cap_factor: 1.1