# @package _global_
# problem args

problem: "cvrp"
graph_size:
coords_dist: 'golden'
out_name: ${problem}_${coords_dist}
data_file_path: data/test_data/cvrp/Golden
normalize_data: False
# checkpoint_load_path: is given in config/model

# RP Env cfg
env_kwargs:
  generator_args:
  sampling_args: