# @package _global_
# problem args

problem: "cvrp"
graph_size: 50
coords_dist: 'uchoa'
out_name: ${problem}_${graph_size}_${coords_dist}
data_file_path: data/test_data/${problem}/${coords_dist}/${problem}${graph_size}/val_seed123_size512.pt
normalize_data: True
checkpoint_load_path: models/MDAM/MDAM/pretrained/vrp_${graph_size}/uniform/epoch-99.pt # uniform ckpt better on uchoa

# RP Env cfg
env_kwargs:
  generator_args:
    coords_sampling_dist: ${coords_dist}
    weights_sampling_dist: ${weights_dist}
    single_large_instance: # data/train_data/${problem}/${coords_dist}/single_large_instance.pt
    normalize_demands: True  # if None or False - demands will remain un-normalized (not between 0-1)
    # if None in the following two args, then all are mixed
    depot_type: E # Depot Position (uchoa only): C = central (500, 500), E = eccentric (0, 0), R = random
    customer_type: R # Customer Position (uchoa only): C = Clustered, RC = Random-Clustered (half half), R = Random
    demand_type: 0  # if None demand will be a mixture of above demand distributions
  sampling_args:
    sample_size: 1024
    graph_size: ${graph_size}
    subsample: False
    k: 12
    cap: 40
    max_cap_factor: # factor of additional capacity w.r.t. a norm capacity of 1.0 per vehicle
    n_depots: 1 #number of depots (default = 1)