# @package _global_
# problem args

problem: "tsp"
graph_size: 20
coords_dist: uniform
out_name: ${problem}_${graph_size}_${coords_dist}
data_file_path: data/test_data/${problem}/${coords_dist}/${problem}${graph_size}/test_seed1234.pkl
normalize_data: True
checkpoint_load_path: models/MDAM/MDAM/pretrained_${problem}${graph_size}/${problem}_${graph_size}/epoch-99.pt


# RP Env cfg
env_kwargs:
  generator_args:
    coords_sampling_dist: ${coords_dist}
    single_large_instance: # data/train_data/${problem}_10000/${coords_dist}/single_large_instance.pt
  sampling_args:
    sample_size: 64
    graph_size: ${graph_size}
    subsample: False