# @package _global_
# problem args

problem: "cvrp"
graph_size: 100
coords_dist: 'uniform'
out_name: ${problem}_${graph_size}_${coords_dist}
data_file_path: data/test_data/${problem}/${coords_dist}/${problem}${graph_size}/val_seed4321_size512.pkl
normalize_data: True
checkpoint_load_path: models/BQ/bq_nco/pretrained_models/cvrp.best

# RP Env cfg
env_kwargs:
  generator_args:
    coords_sampling_dist: ${coords_dist}
    weights_sampling_dist: random_int
    normalize_demands: False  # if None or False - demands will remain un-normalized (not between 0-1)
    single_large_instance: # data/train_data/${problem}/${coords_dist}/single_large_instance.pt
  sampling_args:
    sample_size: 2 # 64
    graph_size: ${graph_size}
    subsample: False
    k: 32
    cap: 50
    n_depots: 1 #number of depots (default = 1)