# @package _global_
# problem args

problem: "cvrp"
graph_size: 200
coords_dist: 'rotation'
weights_dist: 'random_int'
out_name: ${problem}_${graph_size}_${coords_dist}
data_file_path: data/test_data/${problem}/${coords_dist}/${problem}${graph_size}/val_R_size2000.pkl
normalize_data: False
checkpoint_load_path: models/BQ/bq_nco/pretrained_models/cvrp.best


# RP Env cfg
env_kwargs:
  generator_args:
    coords_sampling_dist: ${coords_dist}
    weights_sampling_dist: random_int # sampling integers from 1-10
    normalize_demands: False  # if None or False - demands will remain un-normalized (not between 0-1)
    single_large_instance: # data/train_data/${problem}_10000/${coords_dist}/single_large_instance.pt
    pm: 0.4
  sampling_args:
    sample_size: 64
    graph_size: ${graph_size}
    subsample: False
    k: 20
    cap: 70
    max_cap_factor: # factor of additional capacity w.r.t. a norm capacity of 1.0 per vehicle
    n_depots: 1 #number of depots (default = 1)

