# @package _global_
# policy config

policy: "SGBS_EAS"


model_cfg:
  embedding_dim: 128
  sqrt_embedding_dim: 11.3137 # 128**(1/2)
  encoder_layer_num: 6
  qkv_dim: 16
  head_num: 8
  logit_clipping: 10
  ff_hidden_dim: 512
  eval_type: 'argmax'

run_args:
  cuda_device_num: ${tester_cfg.cuda_device_num}
  num_episodes: ${tester_cfg.test_episodes}
  index_begin: 0
  solution_max_length: 200  # for buffer length storing solution --> args.problem_size*2
  num_eas_sgbs_loop: 28 # 14 #28
  # EAS Params
  lr: 0.0041
  lambda: 0.01
  beta: 0.00
  eas_num_iter: 1
  eas_batch_size: 180
  # SGBS Params
  beam_width: 4 # 1  need 1 with single trajectory aka greedy rollout
  rollout_per_node: 3 # 4-1
  sgbs_batch_size: 3000
