# @package _global_
# problem args

problem: "tsp"
graph_size: 200
coords_dist: "explosion"
out_name: ${problem}_${graph_size}_${coords_dist}
data_file_path: data/test_data/${problem}/${coords_dist}/${problem}${graph_size}/val_E_size2000.pkl
normalize_data: True
checkpoint_load_path: models/NeuroLKH/NeuroLKH/pretrained/neurolkh.pt

# RP Env cfg
env_kwargs:
  generator_args:
    coords_sampling_dist: ${coords_dist}
    single_large_instance: # data/train_data/${problem}_10000/${coords_dist}_rndint/single_large_instance.pt
    radius: 0.35
    beta_exp: 8  # scale value for exponential distribution used in explosion mutation
  sampling_args:
    # sample_size: 1
    graph_size: ${graph_size}
    subsample: False
