# @package _global_
# problem args

problem: "tsp"
graph_size: 200
coords_dist: 'explosion'
out_name: ${problem}_${graph_size}_${coords_dist}
data_file_path: data/test_data/${problem}/${coords_dist}/${problem}${graph_size}/val_E_size2000.pkl
normalize_data: True  # BQ only needs demands normalized - so here we want normalized coords
checkpoint_load_path: models/NeuOpt/NeuOpt/pretrained/tsp100_exp.pt
# models/NeuOpt/NeuOpt/pretrained/tsp${graph_size}.pt


# RP Env cfg
env_kwargs:
  generator_args:
    coords_sampling_dist: ${coords_dist}
    single_large_instance: # data/train_data/${problem}_10000/${coords_dist}/single_large_instance.pt
    radius: 0.35
    beta_exp: 8  # scale value for exponential distribution used in explosion mutation
  sampling_args:
    sample_size: 1024
    graph_size: ${graph_size}
    subsample: False


# model specific env features
wo_feature1: true # remove VI features
wo_feature3: true # remove ES features
dummy_rate: 0.5
warm_up: 0.25